cors:
  originPatterns: "http://localhost:3000,http://localhost:8080"
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_db?useTimezone=true&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: false
springdoc:
  paths-to-match: /**
  swagger-ui:
    use-root-path: true
