spring:
  datasource:
    dbcp2:
      driver-class-name: com.nysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/spring_db?useTimezone=true&serverTimezone=UTC
      username: root
      password: 1234
  jpa:
